# Generated by Django 5.1.1 on 2024-09-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_question_category_alter_question_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='content_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/media'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='content_text_left',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='content_text_right',
            field=models.TextField(blank=True, null=True),
        ),
    ]
