# Generated by Django 5.1.1 on 2024-09-16 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productcategory_content_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='content_text_left',
            new_name='preparation_offline',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='content_text_right',
            new_name='preparation_online',
        ),
    ]
