# Generated by Django 5.1.1 on 2024-09-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_rename_photo_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='content_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/products/categories/'),
        ),
    ]
