# Generated by Django 5.1.1 on 2024-09-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_productdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_guide',
            field=models.BooleanField(default=False),
        ),
    ]
