# Generated by Django 5.1.1 on 2024-09-24 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_is_guide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_guide',
        ),
    ]
