# Generated by Django 5.1.1 on 2024-09-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_remove_product_is_guide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_czk', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_eur', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/products/products/')),
                ('file', models.FileField(upload_to='media/products/guides/')),
                ('slug', models.SlugField(max_length=128, unique=True)),
            ],
        ),
    ]
