# Generated by Django 5.1.1 on 2024-09-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_guide'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotUserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_first_name', models.CharField(max_length=128)),
                ('reviewer_last_name', models.CharField(max_length=128)),
                ('reviewer_image', models.ImageField(upload_to='media/products/reviews/')),
                ('review', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
