# Generated by Django 5.1.1 on 2024-09-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_remove_guide_file_guide_gdrive_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notuserreview',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
