# Generated by Django 5.1.1 on 2024-09-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_notuserreview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notuserreview',
            name='date',
            field=models.DateField(),
        ),
    ]
