# Generated by Django 5.1.1 on 2024-10-12 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_carouselimage_image_alter_guide_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='product',
        ),
    ]
