# Generated by Django 5.1.1 on 2024-10-14 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_remove_question_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideCarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/products/guides/images_for_carousel/')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.guide')),
            ],
        ),
    ]
