# Generated by Django 5.1.1 on 2024-10-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_guide_image_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='img_offline',
            field=models.ImageField(blank=True, null=True, upload_to='media/products/categories/'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='img_online',
            field=models.ImageField(blank=True, null=True, upload_to='media/products/categories/'),
        ),
    ]
