# Generated by Django 5.1.1 on 2024-10-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_productcategory_img_offline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='img_offline',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='img_online',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='gdrive_img_offline',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='gdrive_img_online',
            field=models.URLField(blank=True, null=True),
        ),
    ]
