# Generated by Django 5.1.1 on 2024-09-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_scheduledate_userservices_date_of_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledate',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
