# Generated by Django 5.1.1 on 2024-09-21 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_userservices_file_delete_servicefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userservices',
            name='date_of_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.scheduledate'),
        ),
    ]
