# Generated by Django 5.1.1 on 2024-09-25 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_guide'),
        ('users', '0022_emailverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGuides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_purchase', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.IntegerField(choices=[(0, 'Not Paid'), (1, 'Prepayment'), (2, 'Paid')], default=0)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.guide')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
