# Generated by Django 5.1.1 on 2024-09-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_remove_userservices_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userservices',
            name='gdrive_file_url',
        ),
        migrations.AddField(
            model_name='userservices',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/service_files/'),
        ),
    ]
