# Generated by Django 5.1.1 on 2024-09-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_remove_userservices_gdrive_file_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userservices',
            name='file',
        ),
        migrations.AddField(
            model_name='userservices',
            name='gdrive_file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
