# Generated by Django 5.1.1 on 2024-10-11 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='expiration',
        ),
    ]
