# Generated by Django 5.1.1 on 2024-10-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_event_userservices_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userservices',
            name='status',
            field=models.CharField(choices=[('offline', 'Оффлайн'), ('online', 'Онлайн')], default='offline'),
        ),
    ]
