# Generated by Django 5.1.1 on 2024-10-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_userservices_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userservices',
            name='status',
            field=models.CharField(blank=True, choices=[('offline', 'Оффлайн'), ('online', 'Онлайн')], default='offline', null=True),
        ),
    ]
