# Generated by Django 5.1.1 on 2024-10-15 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_userservices_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userservices',
            name='status',
        ),
    ]
