# Generated by Django 5.1.1 on 2024-10-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_remove_userservices_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userservices',
            name='status',
            field=models.CharField(choices=[('offline', 'Оффлайн'), ('online', 'Онлайн')], default='offline'),
            preserve_default=False,
        ),
    ]
